### ISSUE TITLE
Investigating PAT

### ISSUE THREAD

**Issue by constantinhager** [PSProfileSync/PSProfileSync#1]
- Can we create a PAT our selves if the user has logged in into GitHub?
- Do the user need to create his own PAT and provide It to us?

**Comment by it-joe** [comment]
After reading through the "[OAuth Authorizations API](https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app-and-fingerprint)" it is not clear if chapter "[Get-or-create an authorization for a specific app](https://developer.github.com/v3/oauth_authorizations/#get-or-create-an-authorization-for-a-specific-app)" can be used for any other user than yourself. 

- Besides that, the article is specifically written for OAuth applications - can PSProfileSync be classified as such?
- This method returns a response in JSON, which includes a PADT.

**Comment by it-joe** [comment]
API Implemented. Case Closed.
